services:
  privoxy:
    build: .
    container_name: privoxy
    restart: unless-stopped
    ports:
      - "8118:8118"
    env_file:
      - .env
    networks:
      - proxy-net

networks:
  proxy-net:
    driver: bridge
